# Generated by Django 5.2.5 on 2025-08-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_creator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfasystemconnection',
            name='admin_locked',
            field=models.BooleanField(default=True, help_text='Connection locked by system administrator'),
        ),
        migrations.AddField(
            model_name='mfasystemconnection',
            name='can_disconnect',
            field=models.BooleanField(default=False, help_text='Only system admins can enable disconnection'),
        ),
        migrations.AddField(
            model_name='mfasystemconnection',
            name='force_connection',
            field=models.BooleanField(default=True, help_text='Force connection - tenant cannot disable'),
        ),
    ]
